name: 'Build and deploy to MRT PWA DEVELOPMENT'

on:
  # Will work only on manual execution
  workflow_dispatch:

jobs:
  identification:
    runs-on: ubuntu-latest
    steps:
      - name: 'Action executed by: ${{ github.actor }}'
        run: echo "Action executed by ${{ github.actor }}"
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_SLUG: 'vbq'
      TARGET_SLUG: 'pwa-development'

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install application's dependencies
        run: npm install

      - name: Save credentials
        run: npx @salesforce/pwa-kit-dev@latest save-credentials --user ${{secrets.MRT_API_USER}} --key ${{secrets.MRT_API_TOKEN}}

      - name: Push and deploy the bundle to MRT
        run: npm run push -- --wait -m "${{github.GITHUB_REF}}" -s "${{ env.PROJECT_SLUG }}" -t "${{ env.TARGET_SLUG }}"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      SLACK_CHANNEL: 'vilebrequin-composable-ext'
      TARGET_URL: 'https://vbq-pwa-development.mobify-storefront.com/'

    steps:
      - name: Notify Slack channel
        run: |
          curl \
            -X POST \
            https://slack.com/api/chat.postMessage \
            -H "Content-Type: application/json; charset=utf-8" \
            -H "Authorization: Bearer ${{ secrets.SLACK_BEARER_TOKEN}}" \
            --data '{ "channel": "${{ env.SLACK_CHANNEL }}", "unfurl_links": false, "unfurl_media": false, "blocks": [{ "type": "context", "elements": [{ "type": "mrkdwn", "text": " :tada: :tada: :tada: * RELEASE `${{github.ref_name}}` by ${{ github.actor }} *" }, { "type": "image", "image_url": "https://previews.123rf.com/images/kchung/kchung1505/kchung150500734/39872812-stamp-new-release-in-red-over-white-background.jpg", "alt_text": "images" }] }, { "type": "context", "elements": [{ "type": "mrkdwn", "text": "*Title: ${{github.ref_name}}*" }] }, { "type": "context", "elements": [{ "type": "mrkdwn", "text": ":white_check_mark: Deployed Bundle ${{steps.store-bundle-id.outputs.value}} to <${{ env.TARGET_URL }}|${{ env.TARGET_SLUG }}>" }]}]}'